# Generated by Django 5.0.3 on 2024-05-02 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Limpieza_puestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_limpieza', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=6)),
                ('puesto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.puestos')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_objetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_objeto', models.CharField(max_length=20)),
                ('tipo_objeto', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=6)),
                ('puesto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.puestos')),
            ],
        ),
    ]
