# Generated by Django 5.0.3 on 2024-05-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limpieza_puestos',
            old_name='puesto_id',
            new_name='puesto',
        ),
        migrations.RenameField(
            model_name='registro_objetos',
            old_name='puesto_id',
            new_name='puesto',
        ),
        migrations.AddField(
            model_name='registro_objetos',
            name='servicio',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
