# Generated by Django 5.0.3 on 2024-05-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_limpieza_puestos_usuario_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limpieza_puestos',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.puestos'),
        ),
        migrations.AlterField(
            model_name='registro_objetos',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.puestos'),
        ),
    ]
