# Generated by Django 5.0.3 on 2024-05-06 21:03
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_alter_limpieza_puestos_puesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limpieza_puestos',
            name='horario_limpieza',
            field=models.TimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
