# Generated by Django 5.0.3 on 2024-05-06 21:12
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_remove_limpieza_puestos_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='limpieza_puestos',
            name='horario',
            field=models.TimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
