# Generated by Django 5.0.3 on 2024-05-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_limpieza_puestos_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limpieza_puestos',
            old_name='horario',
            new_name='horario_limpieza',
        ),
    ]
