# Generated by Django 5.0.3 on 2024-05-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0009_rename_horario_limpieza_puestos_horario_limpieza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limpieza_puestos',
            old_name='horario_limpieza',
            new_name='hora',
        ),
    ]
