# Generated by Django 5.0.3 on 2024-05-06 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0011_remove_limpieza_puestos_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='limpieza_puestos',
            name='horario_limpieza',
            field=models.TimeField(default=datetime.datetime(2024, 5, 6, 21, 30, 13, 259714, tzinfo=datetime.timezone.utc)),
        ),
    ]
