# Generated by Django 5.0.3 on 2024-05-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0012_limpieza_puestos_horario_limpieza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limpieza_puestos',
            name='horario_limpieza',
            field=models.TimeField(),
        ),
    ]
