# Generated by Django 5.0.3 on 2024-04-30 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=25)),
                ('permiso', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cargo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.cargo_usuarios'),
            preserve_default=False,
        ),
    ]
