# Generated by Django 5.0.3 on 2024-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_usuarios_cargo_id_alter_usuarios_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_servicio',
            name='correo',
            field=models.EmailField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
