# Generated by Django 5.0.3 on 2024-05-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_cargo_usuarios_usuario_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_servicio',
            name='nombre_empresa',
            field=models.CharField(default='Majos', max_length=30),
            preserve_default=False,
        ),
    ]
