# Generated by Django 5.0.3 on 2024-05-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freidora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambio_aceite',
            name='puesto',
            field=models.CharField(default='COCINA', max_length=20),
            preserve_default=False,
        ),
    ]
