# Generated by Django 5.0.3 on 2024-05-06 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_cargo_usuarios_usuario_servicio_and_more'),
        ('parametros', '0013_alter_limpieza_puestos_horario_limpieza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_limpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=6)),
                ('limpieza_puestos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.limpieza_puestos')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.usuarios')),
                ('usuario_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.usuario_servicio')),
            ],
        ),
    ]
