# Generated by Django 5.0.3 on 2024-05-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limpieza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_limpieza',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
