# Generated by Django 5.0.3 on 2024-05-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_cargo_usuarios_usuario_servicio_and_more'),
        ('parametros', '0004_alter_limpieza_puestos_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio_tempe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('horario', models.CharField(max_length=15)),
                ('registro_objeto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.registro_objetos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.usuarios')),
            ],
        ),
    ]
