# Generated by Django 5.0.3 on 2024-05-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_cargo_usuarios_usuario_servicio_and_more'),
        ('nevera', '0002_cambio_tempe_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambio_tempe',
            name='usuario_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='login.usuario_servicio'),
            preserve_default=False,
        ),
    ]
